### PR TITLE
fixed authorizations in projectview

### LINKED ISSUE #386: Display 404 on invalid project ID

### PR DESCRIPTION
**Pull request by AronBuzogany**
Closes #386

### CODE REVIEW

File: frontend/src/loaders/project-view-loader.ts [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+
+    courseData["admins"] = courseData["admins"].map((admin: string) => {
+      const urlSplit = admin.split("/");
+      return urlSplit[urlSplit.length - 1];
+    });
+
+    const isAdmin =
+      me.uid === courseData["teacher"] || courseData["admins"].includes(me.uid);
+
+    console.log(courseData);
```
Comment (Gerwoud) [inline frontend/src/loaders/project-view-loader.ts]: console.log?

File: frontend/src/pages/project/projectView/ProjectView.tsx [hunk 2]
```diff
@@ -43,129 +49,86 @@ interface Project {
  * and submissions of the current user for that project
  */
 export default function ProjectView() {
-
   const location = useLocation();
-  const [me, setMe] = useState<Me | null>(null);
 
-  const { t } = useTranslation('translation', { keyPrefix: 'projectView' });
+  const { me, projectData, courseData, assignmentText, isAdmin } =
```
Comment (Gerwoud) [inline frontend/src/pages/project/projectView/ProjectView.tsx]: Linter me is assigned but never used?

File: frontend/src/pages/project/projectView/ProjectView.tsx [hunk 3]
```diff
@@ -293,12 +279,15 @@ export default function ProjectView() {
                     }, 4000);
                   }}
                 >
-                  <Box sx={{ border: 1, p: 1, bgcolor: 'background.paper' }}>
-                    <Typography>Are you sure you want to delete this project</Typography>
-                    <Box display="flex"
+                  <Box sx={{ border: 1, p: 1, bgcolor: "background.paper" }}>
+                    <Typography>
+                      Are you sure you want to delete this project
```
Comment (Gerwoud) [inline frontend/src/pages/project/projectView/ProjectView.tsx:284]: Maybe add quick translation to this since you're working on these files already :smile:

**Review by Vucis — APPROVED** [review]

**Review by Gerwoud — CHANGES_REQUESTED** [review]
Great work, it's nice to see you improving :fire: 
image

File: frontend/src/loaders/project-view-loader.ts (hunk 1 above)
Comment (AronBuzogany) [reply frontend/src/loaders/project-view-loader.ts]: Please, review the up to date version, as Github clearly says, this is outdated

File: frontend/src/pages/project/projectView/ProjectView.tsx (hunk 2 above)
Comment (AronBuzogany) [reply frontend/src/pages/project/projectView/ProjectView.tsx]: Same here

File: frontend/src/pages/project/projectView/ProjectView.tsx (hunk 3 above)
Comment (AronBuzogany) [reply frontend/src/pages/project/projectView/ProjectView.tsx:284]: No

Comment (AronBuzogany) [reply frontend/src/pages/project/projectView/ProjectView.tsx]: [a6f6947](https://github.com/SELab-2/UGent-3/pull/418/commits/a6f6947b566fa78afbdc11722c3012421a00a497)

**Review by Gerwoud — APPROVED** [review]
Great work :fire:
